name: ci

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, ubuntu-latest, windows-latest]
                node: [16.x]

        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.23.6
                  run_install: true
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: 'pnpm'

            - run: pnpm format:check
            # - run: pnpm build
            # - run: pnpm lint
            # - run: pnpm test -- --coverage

            # - name: Upload coverage
            #   uses: codecov/codecov-action@v2
            #   with:
            #     name: ${{ matrix.os }}-${{ matrix.node }}
            #     files: ./coverage/lcov.info
