name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test:main


  preload:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test:preload


  site:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test:site


  e2e:
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test:e2e
